[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
gfx_task = "5ebgqSXrqAAG2oofweypArHP5hqgaDh9EnSTau8GtD7g"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ademola/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
