[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
savings_program = "BYDhC79wks4E3P5Fi5Ez4oKwS8fM1PQFVnRQLZsa4YdP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ademola/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
